# Modul 9 Praktikum Sains Data: Pengantar PyTorch

Kembali ke [Sains Data](./saindat2024genap.qmd)

Ini adalah pertemuan terakhir praktikum Sains Data tahun ini.

Di dua pertemuan sebelumnya, kita sudah membahas tentang *neural network* dan *deep learning* dengan TensorFlow dan Keras. Dari segi materi mata kuliah Sains Data, sebenarnya kita sudah selesai.

Namun, di awal [Modul 7](./modul7.ipynb), telah disebutkan bahwa ada dua *framework* utama yang umum digunakan untuk *deep learning* di Python, yaitu TensorFlow (dengan Keras) dan PyTorch.

Agar wawasan kita lebih luas dan tidak terbatas satu *framework* saja, tidak ada salahnya kita coba mempelajari PyTorch juga :)

Lagipula, untuk riset/penelitian di dunia *deep learning*, saat ini PyTorch jauh lebih sering digunakan dibandingkan TensorFlow:

![(Gambar tren November 2014 hingga April 2024: dari semua implementasi atau kode yang telah dibuat untuk paper *deep learning*, berapa persen menggunakan *framework* tertentu. Pada April 2024, persentase PyTorch lebih dari 50%, sedangkan persentase TensorFlow kurang dari 10%.)](./gambar/paperswithcode_nov14_apr24.png)

Gambar tren November 2014 hingga April 2024: dari semua implementasi atau kode yang telah dibuat untuk paper *deep learning*, berapa persen menggunakan *framework* tertentu. Pada April 2024, persentase PyTorch lebih dari 50%, sedangkan persentase TensorFlow kurang dari 10%.

Kalian bisa *explore* di *link* berikut: <https://paperswithcode.com/trends>

Apabila sewaktu-waktu kalian ingin menjalani skripsi atau semacamnya di dunia *deep learning*, atau setidaknya ingin membaca riset terbaru, kami harap wawasan tentang PyTorch ini bermanfaat.

::: {.callout-note}
## Tentang urutan materi

Kami sengaja mengajarkan TensorFlow dan Keras terlebih dahulu, baru mengajarkan PyTorch, karena penulisan kode di PyTorch mirip dengan penggunaan *subclassing API* di Keras.

:::

Sebelum kita mulai, instal terlebih dahulu PyTorch, dengan menginstal `torch` dan `torchvision`

In [ ]:
pip install torch torchvision

- `torch` adalah PyTorch.
- `torchvision` menyediakan fitur-fitur yang membantu ketika berurusan dengan gambar, bahkan seperti sudah menjadi bagian yang tidak terpisahkan dari `torch`.
- Sebenarnya ada juga `torchaudio` yang membantu ketika berurusan dengan data suara. Boleh saja kalian instal juga:

    `pip install torch torchvision torchaudio`

Terkait penginstalan PyTorch, kalian bisa membaca lebih lanjut di sini: <https://pytorch.org/get-started/locally/>

Kalau sudah instal, jangan lupa *import*:

In [1]:
import torch, torchvision

Kita bisa lihat versinya (mungkin di kalian akan lebih baru):

In [3]:
print(torch.__version__)

2.1.0


In [4]:
print(torchvision.__version__)

0.16.0


Jangan lupa *import* juga *library* yang biasa kita gunakan:

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Mengenal PyTorch

### CPU, GPU, dan *device-agnostic code*

Tiap komputer bisa memiliki kekuatan yang berbeda, termasuk ada/tiadanya komponen yang bernama GPU.

Tiap komputer pasti punya yang namanya CPU atau *Central Processing Unit*, yang biasanya menjadi pusat segala komputasi di komputer itu, sesuai namanya.

Namun, untuk perhitungan dengan matriks, tensor atau semacamnya, GPU atau *Graphics Processing Unit* lebih cepat. Perhitungan seperti itu biasa dilakukan untuk tampilan atau *graphics* ketika sedang bermain *game*, dan juga biasa dilakukan ketika berurusan dengan *neural network*.

Sehingga, daripada menggunakan CPU, ada baiknya menggunakan GPU, **kalau ada**.

Di Google Colaboratory, di menu `Runtime > Change runtime type`, di bagian *hardware accelerator*, kalian bisa mengubah *setting*, apakah ingin menggunakan CPU atau GPU. (Bahkan, ada juga TPU atau *tensor processing unit* yang sepertinya lebih dikhususkan lagi untuk komputasi dengan tensor.)

![](./gambar/colabgpu_runtime.png)

![](./gambar/colabgpu_hardware_accelerator.png)

Apapun yang tersedia, **tiap kali kita ingin menggunakan PyTorch,** sebaiknya kita beritahu, mana yang ingin kita gunakan. Agar tidak berantakan, caranya bisa dengan kode berikut:

In [2]:
# Setup device-agnostic code 
if torch.cuda.is_available():
    device = "cuda" # NVIDIA GPU
elif torch.backends.mps.is_available():
    device = "mps" # Apple GPU
else:
    device = "cpu" # Defaults to CPU if NVIDIA GPU/Apple GPU aren't available

print(f"Using device: {device}")

Using device: cpu


Sumber kode: <https://www.learnpytorch.io/pytorch_cheatsheet/#device-agnostic-code-using-pytorch-on-cpu-gpu-or-mps>

*Output* nya akan sesuai dengan pilihan terbaik yang ada, antara CPU atau GPU. Kebetulan, modul ini di-*render* di laptop yang hanya memiliki CPU.

Kode di atas sebenarnya hanya menyimpan pilihan tersebut sebagai *string* ke dalam variabel `device`. Namun, variabel ini nantinya akan digunakan selama berurusan dengan PyTorch.

Sehingga, apabila kita ingin ganti dari CPU ke GPU atau sebaliknya, kita tinggal mengubah isi variabel `device` ini (misalnya menggunakan kode di atas), tidak perlu mengubah kode PyTorch yang sudah kita buat.

Dengan demikian, kode PyTorch yang sudah kita buat menjadi tidak tergantung *device* yang digunakan (apakah CPU atau GPU), atau disebut *device-agnostic*.

### Tensor

Seperti di TensorFlow, di PyTorch juga ada tensor. Cara membuatnya adalah dengan `torch.tensor`

Contohnya, skalar:

In [10]:
tensor0 = torch.tensor(1.5)

In [11]:
print(tensor0)

tensor(1.5000)


In [12]:
print(type(tensor0))

<class 'torch.Tensor'>


Kita bisa melihat dimensinya (rank/dimensi tensor) melalui `.ndim`

In [13]:
print(tensor0.ndim)

0


Tipe datanya berupa `torch.tensor` tapi kita bisa memperoleh nilai skalarnya dengan `.item()`

In [15]:
tensor0.item()

1.5

In [16]:
type(tensor0.item())

float

Contoh lain, array/vektor:

In [8]:
tensor1 = torch.tensor([2.31, 4.567, 8.9])

In [9]:
print(tensor1)

tensor([2.3100, 4.5670, 8.9000])


In [10]:
print(tensor1.ndim)

1


Selain dimensi tensor, ada juga `.shape` yang di sini melambangkan ukuran array/vektor, seperti `.shape` di numpy

In [11]:
print(tensor1.shape)

torch.Size([3])


Nilai suatu elemen di tensor juga bisa diubah:

In [ ]:
tensor1[0] = 52.5

In [ ]:
print(tensor1)

tensor([52.5000,  4.5670,  8.9000])


Ada juga tipe data:

In [16]:
print(tensor1.dtype)

torch.float32


Seperti tensor di TensorFlow, tensor di PyTorch juga biasanya menggunakan bilangan *float* yang 32-bit daripada 64-bit.

Contoh lagi, matriks:

In [3]:
mat1 = torch.tensor([
    [1, 2.718, 3.14],
    [4, 5, 6.28]
])

In [4]:
print(mat1)

tensor([[1.0000, 2.7180, 3.1400],
        [4.0000, 5.0000, 6.2800]])


In [5]:
print(mat1.ndim)

2


In [6]:
print(mat1.shape)

torch.Size([2, 3])


Kita bisa buat matriks kedua, lalu mengalikannya dengan perkalian matriks menggunakan `torch.matmul`

In [19]:
mat2 = torch.tensor([
    [9, 8],
    [7, 6],
    [5, 4.3]
])

In [23]:
print(mat2.ndim)
print(mat2.shape)
print(mat2.dtype)

2
torch.Size([3, 2])
torch.float32


In [21]:
mat3 = torch.matmul(mat1, mat2)

In [22]:
print(mat3)

tensor([[ 43.7260,  37.8100],
        [102.4000,  89.0040]])


Matriks juga bisa ditranspos dengan `.T`

In [38]:
mat4 = mat3.T
print(mat4)

tensor([[ 43.7260, 102.4000],
        [ 37.8100,  89.0040]])


### Konversi dari/ke numpy

Kita bisa mengonversi tensor PyTorch menjadi array numpy dan sebaliknya:

- `.numpy()` untuk mengubah suatu tensor PyTorch menjadi array numpy

- `torch.from_numpy(...)` untuk mengubah suatu array numpy menjadi tensor PyTorch

In [43]:
arr5 = mat4.numpy()
print(arr5)
print(type(arr5))
print(arr5.dtype)

[[ 43.725998 102.4     ]
 [ 37.809998  89.004   ]]
<class 'numpy.ndarray'>
float32


In [42]:
mat6 = torch.from_numpy(arr5)
print(mat6)
print(type(mat6))
print(mat6.dtype)

tensor([[ 43.7260, 102.4000],
        [ 37.8100,  89.0040]])
<class 'torch.Tensor'>
torch.float32


### ones, zeros, rand, randn

Kita bisa membuat tensor berisi satu semua, atau nol semua, atau nilai random, dengan ukuran `size` yang bisa kita tentukan

In [26]:
x = torch.ones(size = (3,4))
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [25]:
x = torch.zeros(size = (3,4))
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [28]:
x = torch.rand(size = (3,4))
print(x)

tensor([[0.0698, 0.2004, 0.3279, 0.2525],
        [0.2461, 0.4263, 0.4870, 0.4371],
        [0.9545, 0.7487, 0.3990, 0.0412]])


`torch.rand` memilih nilai secara random dari distribusi uniform pada interval $[0,1)$

Untuk memilih nilai secara random dari distribusi normal (dengan $\mu = 0$ dan $\sigma = 1$), gunakan `torch.randn`

In [68]:
x = torch.randn(size = (3,4))
print(x)

tensor([[ 1.5820, -0.1806,  0.1820, -0.6891],
        [ 1.2161, -0.5755, -0.5172, -0.7454],
        [ 0.3047, -0.5932, -0.3343, -1.1461]])


### Operasi tensor seperti numpy

Secara umum, operasi tensor di PyTorch memang mirip dengan array di numpy, sebagaimana operasi tensor di TensorFlow juga mirip dengan array di numpy.

In [29]:
a = 4 * torch.ones((2, 2))
print(a)

tensor([[4., 4.],
        [4., 4.]])


In [30]:
b = torch.square(a)
print(b)

tensor([[16., 16.],
        [16., 16.]])


In [31]:
c = torch.sqrt(a)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [32]:
d = b + c
print(d)

tensor([[18., 18.],
        [18., 18.]])


In [34]:
# perkalian matriks
e = torch.matmul(a, c)
print(e)

tensor([[16., 16.],
        [16., 16.]])


In [35]:
# perkalian per elemen
e *= d
print(e)

tensor([[288., 288.],
        [288., 288.]])


In [36]:
# penjumlahan per elemen
f = e + 2
print(f)

tensor([[290., 290.],
        [290., 290.]])


### *Autograd* dengan `.backward()`

Sebagaimana ada *automatic differentiation* atau *autodiff* di TensorFlow, ada juga autograd di PyTorch. Namun, *syntax* nya cukup berbeda.

Caranya, inputnya kita jadikan tensor dengan parameter `requires_grad=True`, lalu kita operasikan (misal dengan fungsi f) dan menghasilkan tensor baru, lalu di tensor baru ini kita panggil `.backward()` agar turunan f dihitung dan disimpan di variabel input `.grad`

Contohnya, turunan $x^3$ terhadap $x$ di $x=4$ adalah $3(4)^2 = 48$.

In [46]:
# siapkan input, dengan requires_grad=True
x = torch.tensor(4.0, requires_grad=True)

# hitung fungsi F
F = x**3

# jalankan perhitungan turunan F (terhadap input)
F.backward()

# tampilkan turunan yang tersimpan di input .grad
print(x.grad)

tensor(48.)


Nama *method* nya adalah `.backward()` dan memang digunakan di *backward pass* (akan kita lihat nanti).

Contoh lain, turunan $3x^3 - y^2$ terhadap $x$ dengan $x=2$ adalah $9(2)^2 = 36$, dan turunannya terhadap $y$ dengan $y=6$ adalah $-2(6) = -12$

In [49]:
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(6.0, requires_grad=True)

F = 3 * x**3 - y**2

F.backward()

print(x.grad)
print(y.grad)

tensor(36.)
tensor(-12.)


## Klasifikasi biner dengan *perceptron*

### Persiapan data, `TensorData`, `DataLoader`

Untuk model pertama kita, mari kita coba buat kembali model *perceptron* untuk klasifikasi biner yang pernah kita buat di [Modul 7](./modul7.ipynb), dengan dataset `titik_negatif_positif.csv` yang sama, bisa kalian *download* dari GitHub Pages ini: [titik_negatif_positif.csv](./titik_negatif_positif.csv)

Kita buka datasetnya, jangan lupa dengan `dtype="float32"` karena itulah tipe data yang biasa digunakan oleh PyTorch, seperti TensorFlow:

In [52]:
titik_df = pd.read_csv("./titik_negatif_positif.csv", dtype="float32")

In [53]:
titik_df

x         y  kelas
0     1.173375  4.570637    0.0
1     0.195961  3.504604    0.0
2     0.121400  2.163783    0.0
3    -1.170182  3.882771    0.0
4    -0.424403  0.534641    0.0
...        ...       ...    ...
1995  2.423160 -0.337196    1.0
1996  1.949836 -0.627813    1.0
1997  2.109928 -0.382492    1.0
1998  4.178664  0.486168    1.0
1999  2.326363  1.228249    1.0

[2000 rows x 3 columns]

Memisahkan antara inputs (prediktor) dan targets (variabel target):

In [54]:
titik_inputs_df = titik_df.drop(columns=["kelas"])
titik_targets_df = titik_df[["kelas"]]

In [55]:
titik_inputs_df

x         y
0     1.173375  4.570637
1     0.195961  3.504604
2     0.121400  2.163783
3    -1.170182  3.882771
4    -0.424403  0.534641
...        ...       ...
1995  2.423160 -0.337196
1996  1.949836 -0.627813
1997  2.109928 -0.382492
1998  4.178664  0.486168
1999  2.326363  1.228249

[2000 rows x 2 columns]

In [56]:
titik_targets_df

kelas
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
...     ...
1995    1.0
1996    1.0
1997    1.0
1998    1.0
1999    1.0

[2000 rows x 1 columns]

Mengubahnya menjadi *array* numpy:

In [57]:
titik_inputs_arr = titik_inputs_df.to_numpy()
titik_targets_arr = titik_targets_df.to_numpy()

Kemudian mengubahnya menjadi tensor PyTorch:

In [58]:
titik_inputs_tensor = torch.from_numpy(titik_inputs_arr)
titik_targets_tensor = torch.from_numpy(titik_targets_arr)

Tujuan mengubah dari DataFrame menjadi tensor, tentunya supaya bisa diproses dengan PyTorch.

Kita bisa periksa, bentuknya sesuai:

In [60]:
print(titik_inputs_tensor)

tensor([[ 1.1734,  4.5706],
        [ 0.1960,  3.5046],
        [ 0.1214,  2.1638],
        ...,
        [ 2.1099, -0.3825],
        [ 4.1787,  0.4862],
        [ 2.3264,  1.2282]])


In [61]:
print(titik_targets_tensor)

tensor([[0.],
        [0.],
        [0.],
        ...,
        [1.],
        [1.],
        [1.]])


Kemudian, kita bisa melakukan *train-validation-test split*, misalnya dengan rasio 80:10:10

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
# data utuh menjadi data train 80% dan data "test" 20%
titik_X_train, titik_X_test, titik_y_train, titik_y_test = train_test_split(
    titik_inputs_tensor, titik_targets_tensor, test_size=0.2, random_state=42
)

# data "test" dibagi dua, menjadi data validation dan data test sesungguhnya
titik_X_val, titik_X_test, titik_y_val, titik_y_test = train_test_split(
    titik_X_test, titik_y_test, test_size=0.5, random_state=42
)

Kita bisa periksa ukurannya, rasionya sudah sesuai yang kita tetapkan:

In [64]:
print(titik_X_train.shape)
print(titik_X_val.shape)
print(titik_X_test.shape)

torch.Size([1600, 2])
torch.Size([200, 2])
torch.Size([200, 2])


Sebelum dataset kita benar-benar siap untuk diproses dengan PyTorch, ada dua hal yang perlu kita lakukan:

1. mengubahnya menjadi objek `Dataset` dengan `TensorDataset`

    `Dataset` di sini adalah format dataset umum yang dikenal oleh PyTorch.

2. mengubah objek `Dataset` menjadi objek `DataLoader`

    `DataLoader` membuat objek `Dataset` menjadi *"iterable"* yaitu bisa diiterasikan dengan *for loop*, agar bisa digunakan dalam proses *training* maupun *testing*.

Baik `TensorDataset` maupun `DataLoader` bisa kita import dari `torch.utils.data`

In [65]:
from torch.utils.data import TensorDataset, DataLoader

Masing-masing dari data train, data validation, dan data test bisa kita ubah menjadi objek `Dataset` dengan menentukan mana prediktor dan mana target:

In [66]:
titik_train_dataset = TensorDataset(titik_X_train, titik_y_train)
titik_val_dataset = TensorDataset(titik_X_val, titik_y_val)
titik_test_dataset = TensorDataset(titik_X_test, titik_y_test)

Kemudian, masing-masing bisa kita ubah menjadi `DataLoader`, sekasligus menentukan *batch size*, dan juga menentukan apakah perlu ada *shuffling* di tiap epoch (biasanya dilakukan di data *train* untuk mengurangi *overfitting*):

In [67]:
titik_train_dataloader = DataLoader(titik_train_dataset, batch_size=32, shuffle=True)
titik_val_dataloader = DataLoader(titik_val_dataset, batch_size=32, shuffle=False)
titik_test_dataloader = DataLoader(titik_test_dataset, batch_size=32, shuffle=False)

### Menyusun model

Ingat bahwa *perceptron* yang ingin kita susun hanya terdiri dari

- *input layer* dengan dua *neuron*,

- tidak ada *hidden layer*,

- *output layer* dengan satu *neuron* dan fungsi aktivasi sigmoid

Sehingga matriks bobot yang sesuai berukuran $2 \times 1$, dan vektor bias yang sesuai berukuran $1 \times 1$.

Di PyTorch, tiap model berupa *class* dengan ketentuan:

- meng-*inherit* dari `torch.nn.Module` (yaitu *base class* untuk semua model PyTorch)

- baris pertama di *constructor* `__init__` adalah

    `super().__init__()`

- harus mendefinisikan `forward()` untuk *forward pass*

- komponen/variabel/atribut/parameter yang diperlukan biasanya didefinisikan di *constructor*

    Catatan: parameter biasa didefinisikan dengan `torch.nn.Parameter` daripada `torch.tensor`

Ini cukup mirip dengan *subclassing API* di Keras, yang meng-*inherit* dari `keras.Model` dan harus mendefinisikan `call()` untuk *forward pass*.

Mari kita susun *perceptron* kita, yang memiliki matriks bobot, vektor bias, dan fungsi aktivasi sigmoid:

In [69]:
class MyPerceptron(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.weights = torch.nn.Parameter(
            torch.randn(size = (2, 1), dtype = torch.float32),
            requires_grad=True # agar autgrad aktif
        )

        self.bias = torch.nn.Parameter(
            torch.randn(size = (1,), dtype = torch.float32),
            requires_grad=True
        )
    
    def forward(self, x):
        return torch.sigmoid(
            torch.matmul(x, self.weights) + self.bias
        )

Kita bisa buat suatu *instance* atau objek dari *class* di atas:

In [70]:
pisah_titik = MyPerceptron()

Ini adalah model yang siap di-*train*. Sebelum *training*, kita bisa memeriksa parameter model (saat ini masih random sesuai `torch.randn`):

In [72]:
list(pisah_titik.parameters())

[Parameter containing:
 tensor([[-0.9278],
         [-1.5490]], requires_grad=True),
 Parameter containing:
 tensor([-1.0868], requires_grad=True)]

Mirip, ada juga yang namanya `.state_dict()`

In [73]:
pisah_titik.state_dict()

OrderedDict([('weights',
              tensor([[-0.9278],
                      [-1.5490]])),
             ('bias', tensor([-1.0868]))])

### Menyiapkan *hyperparameter*

Untuk klasifikasi, *loss function* yang biasa digunakan adalah *crossentropy loss*, atau mungkin lebih spesifiknya *binary crossentropy loss*, yang disebut `torch.nn.BCELoss` di PyTorch. Kita bisa menyiapkannya sebagai objek.

In [74]:
titik_loss = torch.nn.BCELoss()

Serupa, *optimizer* juga disiapkan sebagai objek, misalnya `torch.optim.SGD` untuk SGD *(stochastic gradient descent)*:

In [ ]:
titik_opt = torch.optim.SGD(params=pisah_titik.parameters(), # merujuk ke parameter model
                            lr=0.01) # learning rate

### *Training loop*

### Prediksi

### `torch.nn.Linear` dan `torch.nn.Sequential`

In [ ]:
class MyPerceptron_v2:
    pass

In [ ]:
class MyPerceptron_v3:
    pass

## Fungsi *train step* dan *test step*

## Klasifikasi Gambar

## Referensi

Internet

- <https://paperswithcode.com/trends>

- <https://pytorch.org/docs/stable/index.html>

Sumber belajar PyTorch, *deep learning*, atau semacamnya, untuk belajar lebih lanjut

- <https://www.learnpytorch.io/>

- Buku *Dive into Deep Learning* (biasa disebut D2L), utamanya menggunakan PyTorch: <https://d2l.ai/>

- Situs bernama *"weights and biases"* (wandb) menyediakan layanan pemantauan proses *training*: <https://wandb.ai/site>