# Modul 7 Struktur Data: *Queue* dan berbagai implementasinya

Kembali ke [Struktur Data (dengan Python)](strukdat2023.qmd)

Di praktikum kali ini, kita akan membahas tentang struktur data *queue* serta berbagai "implementasi"nya dalam Python (yaitu berbagai cara membuat struktur data *queue* di Python), baik menggunakan *array* maupun *linked list*.

*Queue* itu sendiri adalah suatu struktur data dengan dua ujung, di mana data bisa dimasukkan dari salah satu ujung tertentu (yang disebut *rear*) dan data bisa dikeluarkan dari ujung yang satunya lagi (yang disebut *front*). *Queue* dikatakan menganut prinsip FIFO (*First In First Out*), karena data yang pertama masuk akan menjadi data yang pertama keluar.

Kita akan menggunakan *array* dari numpy, sehingga perlu melakukan import:

In [18]:
import numpy as np

## Implementasi (*linear*) *queue* dengan *array*

In [19]:
class ArrayLinQueue:
    def __init__(self, dtype, array_max):
        self.dtype = dtype
        self.array_max = array_max
        self.array = np.empty(array_max, dtype=dtype)
        self.front = -1
        self.rear = -1
    
    def get_size(self):
        size = (self.rear - self.front) + 1
        return size

    def get_capacity_array(self):
        return self.array_max

    def get_capacity_queue(self):
        if self.front == -1:
            capacity_queue = self.array_max
        else:
            capacity_queue = self.array_max - self.front
        return capacity_queue
    
    def is_empty(self):
        if self.front == -1:
            return True
        else:
            return False
    
    def is_full(self):
        if self.rear == self.array_max - 1:
            return True
        else:
            return False
    
    def enqueue(self, newdata):
        if self.is_full():
            print("Error enqueue: queue sudah penuh sebelumnya")
        elif self.front == -1:
            self.front += 1
            self.rear += 1
            self.array[self.rear] = newdata
        else:
            self.rear += 1
            self.array[self.rear] = newdata
    
    def peek(self):
        if self.is_empty():
            print("Error peek: queue sedang kosong")
        else:
            return self.array[self.front]
    
    def dequeue(self):
        if self.is_empty():
            print("Error dequeue: queue sudah kosong sebelumnya")
            return None
        elif (self.get_size() == 1):
            # Jika di queue hanya ada satu elemen, dan ingin di-dequeue,
            # maka queue akan kosong setelah itu
            output = self.array[self.front]
            self.front = -1
            self.rear = -1
            return output
        else:
            output = self.array[self.front]
            self.front += 1
            return output
    
    def print_storage(self):
        print(self.array)

    def print_queue(self):
        print("front : ", end="")
        if self.is_empty():
            print("(tidak ada data) : rear")
        else:
            for i in range(self.front, self.rear): # i = front, ..., rear-1
                print(self.array[i], end=" | ")
            print(self.array[self.rear], end="") # untuk i = rear
            print(" : rear")

In [33]:
arraylinqueue = ArrayLinQueue(int, 5)

In [34]:
arraylinqueue.print_queue()

front : (tidak ada data) : rear


In [35]:
arraylinqueue.print_storage()

[                  0 4602678819172646912 4607182418800017408
 4609434218613702656 4611686018427387904]


In [36]:
arraylinqueue.enqueue(-18)
arraylinqueue.enqueue(67)
arraylinqueue.enqueue(32)

In [37]:
arraylinqueue.print_queue()

front : -18 | 67 | 32 : rear


In [38]:
arraylinqueue.print_storage()

[                -18                  67                  32
 4609434218613702656 4611686018427387904]


In [39]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

0
2


In [40]:
arraylinqueue.enqueue(-29)

In [41]:
arraylinqueue.print_queue()

front : -18 | 67 | 32 | -29 : rear


In [42]:
arraylinqueue.print_storage()

[                -18                  67                  32
                 -29 4611686018427387904]


In [43]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

0
3


In [44]:
print(arraylinqueue.peek())

-18


In [45]:
arraylinqueue.print_queue()

front : -18 | 67 | 32 | -29 : rear


In [46]:
nilai = arraylinqueue.dequeue()
print(nilai)

-18


In [47]:
arraylinqueue.print_queue()

front : 67 | 32 | -29 : rear


In [48]:
arraylinqueue.print_storage()

[                -18                  67                  32
                 -29 4611686018427387904]


In [49]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

1
3


In [50]:
print(arraylinqueue.dequeue())

67


In [51]:
arraylinqueue.print_queue()

front : 32 | -29 : rear


In [54]:
print(arraylinqueue.dequeue())
print(arraylinqueue.dequeue())

32
-29


In [55]:
arraylinqueue.print_queue()

front : (tidak ada data) : rear


In [56]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

-1
-1


In [57]:
print(arraylinqueue.dequeue())

Error dequeue: queue sudah kosong sebelumnya
None


In [58]:
arraylinqueue.enqueue(-25)
arraylinqueue.enqueue(13)
arraylinqueue.enqueue(48)
arraylinqueue.enqueue(-87)
arraylinqueue.enqueue(38)

In [59]:
arraylinqueue.print_queue()

front : -25 | 13 | 48 | -87 | 38 : rear


In [60]:
arraylinqueue.print_storage()

[-25  13  48 -87  38]


In [61]:
print(arraylinqueue.is_full())

True


In [62]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

0
4


In [67]:
arraylinqueue.enqueue(-53)

Error enqueue: queue sudah penuh sebelumnya


In [63]:
print(arraylinqueue.dequeue())
print(arraylinqueue.dequeue())

-25
13


In [64]:
arraylinqueue.print_queue()

front : 48 | -87 | 38 : rear


In [65]:
arraylinqueue.print_storage()

[-25  13  48 -87  38]


In [66]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

2
4


In [68]:
arraylinqueue.enqueue(-53)

Error enqueue: queue sudah penuh sebelumnya


## Implementasi *circular queue* dengan *array*

In [72]:
class ArrayCircQueue:
    def __init__(self, dtype, max):
        self.dtype = dtype
        self.max = max
        self.array = np.empty(max, dtype=dtype)
        self.front = -1
        self.rear = -1
    
    def is_empty(self):
        if self.front == -1:
            return True
        else:
            return False
    
    def is_full(self):
        if self.front == (self.rear + 1) % self.max:
            return True
        else:
            return False

    def get_size(self):
        if self.is_empty():
            size = 0
        elif self.front <= self.rear:
            size = (self.rear - self.front) + 1
        else:
            size = self.max - (self.front - self.rear - 1)
        return size

    def get_capacity(self):
        return self.max
    
    def enqueue(self, newdata):
        if self.is_full():
            print("Error enqueue: queue sudah penuh sebelumnya")
        elif self.front == -1:
            self.front += 1
            self.rear += 1
            self.array[self.rear] = newdata
        else:
            self.rear = (self.rear + 1) % self.max # hanya berbeda di sini
            self.array[self.rear] = newdata
    
    # Masih sama persis
    def peek(self):
        if self.is_empty():
            print("Error peek: queue sedang kosong")
        else:
            return self.array[self.front]
    
    def dequeue(self):
        if self.is_empty():
            print("Error dequeue: queue sudah kosong sebelumnya")
            return None
        elif (self.get_size() == 1):
            # Jika di queue hanya ada satu elemen, dan ingin di-dequeue,
            # maka queue akan kosong setelah itu
            output = self.array[self.front]
            self.front = -1
            self.rear = -1
            return output
        else:
            output = self.array[self.front]
            self.front = (self.front + 1) % self.max # hanya berbeda di sini
            return output
    
    def print_storage(self):
        print(self.array)

    def print_queue(self):
        print("front : ", end="")
        if self.is_empty():
            print("(tidak ada data) : rear")
        else:
            # i = front, ..., rear-1 (kurang lebih begitu)
            i = self.front
            while i != self.rear:
                print(self.array[i], end=" | ")
                i = (i + 1) % self.max
            # untuk i = rear
            print(self.array[self.rear], end="") 
            print(" : rear")

In [142]:
arraycircqueue = ArrayCircQueue(int, 5)
arraycircqueue.print_queue()

front : (tidak ada data) : rear


In [145]:
arraycircqueue.print_storage()

[4607182418800017408 4613374868287651840 4618441417868443648
 4622241330054037504 4625478292286210048]


In [146]:
arraycircqueue.enqueue(65)
arraycircqueue.enqueue(-11)
arraycircqueue.enqueue(43)

In [147]:
arraycircqueue.print_queue()

front : 65 | -11 | 43 : rear


In [148]:
arraycircqueue.print_storage()

[                 65                 -11                  43
 4622241330054037504 4625478292286210048]


In [149]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

0
2


In [150]:
arraycircqueue.enqueue(97)
arraycircqueue.enqueue(-12)

In [151]:
arraycircqueue.print_queue()

front : 65 | -11 | 43 | 97 | -12 : rear


In [152]:
arraycircqueue.enqueue(41)

Error enqueue: queue sudah penuh sebelumnya


In [153]:
arraycircqueue.print_storage()

[ 65 -11  43  97 -12]


In [154]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

0
4


In [155]:
print(arraycircqueue.peek())

65


In [156]:
arraycircqueue.print_queue()

front : 65 | -11 | 43 | 97 | -12 : rear


In [157]:
print(arraycircqueue.dequeue())

65


In [158]:
arraycircqueue.print_queue()

front : -11 | 43 | 97 | -12 : rear


In [159]:
arraycircqueue.print_storage()

[ 65 -11  43  97 -12]


In [160]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

1
4


In [161]:
print(arraycircqueue.dequeue())
print(arraycircqueue.dequeue())

-11
43


In [162]:
arraycircqueue.print_queue()

front : 97 | -12 : rear


In [163]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

3
4


In [164]:
arraycircqueue.print_storage()

[ 65 -11  43  97 -12]


In [165]:
arraycircqueue.enqueue(-74)

In [166]:
arraycircqueue.print_queue()

front : 97 | -12 | -74 : rear


In [167]:
arraycircqueue.print_storage()

[-74 -11  43  97 -12]


In [169]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

3
0


In [170]:
arraycircqueue.enqueue(19)

In [171]:
arraycircqueue.print_queue()

front : 97 | -12 | -74 | 19 : rear


In [172]:
arraycircqueue.print_storage()

[-74  19  43  97 -12]


In [173]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

3
1


In [174]:
arraycircqueue.enqueue(85)

In [175]:
arraycircqueue.print_queue()

front : 97 | -12 | -74 | 19 | 85 : rear


In [176]:
arraycircqueue.print_storage()

[-74  19  85  97 -12]


In [177]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

3
2


In [178]:
arraycircqueue.enqueue(-31)

Error enqueue: queue sudah penuh sebelumnya


In [179]:
print(arraycircqueue.dequeue())

97


In [180]:
arraycircqueue.print_queue()

front : -12 | -74 | 19 | 85 : rear


In [181]:
arraycircqueue.print_storage()

[-74  19  85  97 -12]


In [182]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

4
2


In [183]:
print(arraycircqueue.dequeue())

-12


In [184]:
arraycircqueue.print_queue()

front : -74 | 19 | 85 : rear


In [185]:
arraycircqueue.print_storage()

[-74  19  85  97 -12]


In [186]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

0
2


In [187]:
arraycircqueue.enqueue(27)

In [188]:
arraycircqueue.print_queue()

front : -74 | 19 | 85 | 27 : rear


In [189]:
arraycircqueue.print_storage()

[-74  19  85  27 -12]


In [190]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

0
3


In [191]:
print(arraycircqueue.dequeue())

-74


In [192]:
arraycircqueue.print_queue()

front : 19 | 85 | 27 : rear


In [193]:
arraycircqueue.print_storage()

[-74  19  85  27 -12]


In [194]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

1
3


## Implementasi (*linear*) *queue* dengan *linked list*

In [69]:
class SLNode:
    def __init__(self, data, next=None):
        self.data = data
        self.next = next

In [70]:
class SLLinQueue:
    def __init__(self):
        # head=front, tail=rear
        self.front = None
        self.rear = None
    
    def is_empty(self):
        if self.front == None:
            return True
        else:
            return False
    
    def get_size(self):
        size = 0
        temp = self.front
        while (temp != None):
            size += 1
            temp = temp.next
        return size

    # insert di akhir linked list
    def enqueue(self, newdata):
        newnode = SLNode(newdata)
        if self.is_empty():
            self.front = newnode
            self.rear = newnode
        else:
            self.rear.next = newnode
            self.rear = newnode
    
    def peek(self):
        if self.is_empty():
            print("Error peek: queue sedang kosong")
            return None
        else:
            return self.front.data

    # hapus di awal linked list
    def dequeue(self):
        if self.is_empty():
            print("Error dequeue: queue sudah kosong sebelumnya")
            return None
        else:
            output = self.front.data
            temp = self.front
            self.front = self.front.next
            del temp
            return output
    
    def print_queue(self):
        print("front : ", end="")
        if self.is_empty():
            print("(tidak ada data) : rear")
        else:
            temp = self.front
            while temp != None:
                if temp.next != None:
                    print(temp.data, end = " | ")
                else:
                    print(temp.data, end="")
                temp = temp.next
            print(" : rear")

    def print_storage(self):
        print("front -> ", end="")
        if self.is_empty():
            print("None <- rear")
        else:
            temp = self.front
            while temp != None:
                if temp.next != None:
                    print(temp.data, end = " -> ")
                else:
                    print(temp.data, end = " <- ")
                temp = temp.next
            print("rear")

In [9]:
sllinqueue = SLLinQueue()
sllinqueue.print_queue()
sllinqueue.print_storage()

front : (tidak ada data) : rear
front -> None <- rear


In [10]:
sllinqueue.enqueue(10)
sllinqueue.print_queue()
sllinqueue.print_storage()

front : 10 : rear
front -> 10 <- rear


In [11]:
sllinqueue.enqueue(98)
sllinqueue.print_queue()
sllinqueue.print_storage()

front : 10 | 98 : rear
front -> 10 -> 98 <- rear


In [12]:
sllinqueue.enqueue(-43)
sllinqueue.print_queue()
sllinqueue.print_storage()

front : 10 | 98 | -43 : rear
front -> 10 -> 98 -> -43 <- rear


In [13]:
print(sllinqueue.peek())

10


In [14]:
sllinqueue.print_queue()
sllinqueue.print_storage()

front : 10 | 98 | -43 : rear
front -> 10 -> 98 -> -43 <- rear


In [15]:
print(sllinqueue.dequeue())

10


In [16]:
sllinqueue.print_queue()
sllinqueue.print_storage()

front : 98 | -43 : rear
front -> 98 -> -43 <- rear


## (TODO) Pengayaan: *Deque* atau *double-ended queue* (DEQ)

## (TODO) Implementasi *circular queue* dengan *linked list*