---
title: "TUGAS 3 Praktikum Metode Numerik: Sistem Persamaan Linear"
subtitle: "Assignment"
author:
    - "Laboratorium Komputasi Matematika"
    - "Departemen Matematika FMIPA UI"
description: "Online dan Offline di Departemen Matematika"
date: 05/17/2025
page-navigation: true
format: html
execute:
 enabled: false
---

<style>
.box-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
    margin: 20px 0;
}

.box-card {
    padding: 15px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    transition: transform 0.2s;
    background: white;
    text-align: center;
}

.box-card:hover {
    transform: translateY(-5px);
}

.btn {
    display: inline-block;
    padding: 12px 24px;
    background: linear-gradient(45deg, #4CAF50, #45a049);
    color: white !important;
    text-decoration: none;
    border-radius: 25px;
    font-weight: bold;
    transition: all 0.3s;
    border: none;
    cursor: pointer;
}

.btn:hover {
    background: linear-gradient(45deg, #45a049, #4CAF50);
    box-shadow: 0 4px 15px rgba(0,0,0,0.2);
}
</style>

### Petunjuk Umum:

1. Kerjakan secara Individu
2. Kerjakan tugas ini menggunakan bahasa pemrograman Python dengan file format berupa interactive Python notebook (yaitu file berbentuk .ipynb BUKAN .py), yang bisa dibuat misalnya menggunakan Jupyter Notebook atau Google Colaboratory.
3. **Harap sertakan penjelasan untuk setiap variabel yang digunakan dan setiap proses secara singkat** di samping potongan kode (dengan comment, ‘#'). Selain itu, **sertakan juga penjelasan program** (yang bisa mencakupi idenya apa, bagaimana cara eksekusi program, atau tentang algoritma program yang digunakan) **pada *cell* di sebelah (atas/bawah) program**.
4. Format nama *file* untuk Tugas 2 ini adalah:

    Nama Lengkap_NPM_Kelas SIAK_Tugas2PrakMetnum.ipynb

    Contoh penamaan yang benar:

    Luthfi Athallah Herdita Wiryaman_2206826980_Kelas G_Tugas1PrakMetnum_OnSite.ipynb

    Luthfi Athallah Herdita Wiryaman_2206826980_Kelas G_Tugas1PrakMetnum_OnSite_revisi1.ipynb

5. Pengumpulan tugas dilakukan ke Google Forms berikut ini, sesuai dengan kelas Anda di SIAK NG (link akan selalu sama untuk semua tugas praktikum metode numerik):
- Kelas A: [https://forms.gle/3xguPQVR2HJGbi456](https://forms.gle/7WhpRfnXv1bvmmRb8)
- Kelas B: [https://forms.gle/XfxJAUyAdwDLgMwj6](https://forms.gle/cCM65Q6esQbAzJzp6)
- Kelas C: [https://forms.gle/ihiKuSjU65fpxEZ67](https://forms.gle/RDNKibWRkxh24BBa6)
- Kelas D: [https://forms.gle/15BVmErcputb5NrX8](https://forms.gle/smY8ca8gDCgeSusw5)
- Kelas E: [https://forms.gle/MydWb7kku6iyvdNNA](https://forms.gle/MRdEe2fYUUSzK5xYA)
- Kelas F: [https://forms.gle/RuKXWpwQeu7Jbt5YA](https://forms.gle/sfTdcfZ4t8S9AKLn6)

6. Tenggat waktu pengerjaan Tugas 3 ini adalah Jumat, 6 Juni 2025 pukul 23.59 WIB.
Mohon manfaatkan waktu Anda dengan baik (seperti mencicil pengerjaan, bahkan sudah selesai dari jauh-jauh hari) agar mengumpulkan tugas sebelum deadline. Keterlambatan pengumpulan bisa dikenakan pengurangan nilai atau bahkan dianggap tidak mengumpulkan, tergantung kesepakatan dari dosen. Meskipun demikian, lebih baik terlambat mengumpulkan daripada tidak mengumpulkan sama sekali.

7. Sesuai standar Universitas Indonesia, **plagiarisme dilarang keras** dan bisa menyebabkan nilai tugas praktikum **menjadi nol untuk semua pihak yang terlibat, tanpa peringatan apapun**.

8. *Module* atau *package* Python yang boleh digunakan (di-import) untuk Tugas 2 ini hanyalah numpy, tabulate, matplotlib, dan sympy. Apabila Anda berniat ingin menggunakan module lain, harap konfirmasikan ke narahubung terlebih dahulu (bisa saja diperbolehkan).
Narahubung untuk Tugas 3 Praktikum Metode Numerik adalah:
    - 📞 Fasya (LINE: ifasyai)



### Sistem Persamaan Linier

Bentuk umum dari suatu sistem persamaan linier (SPL) diberikan oleh :
$$\boldsymbol{Ax} = \boldsymbol{b}$$

Misalkan $a_{i,j}$ menyatakan nilai dari baris ke $i$ dan kolom ke $j$ pada $\boldsymbol{A}$, dan $b_i$ menyatakan nilai dari baris ke $i$ pada $\boldsymbol{b}$. Jika didefinisikan $a_{i,j}$ dan $b_i$ sebagai berikut:
$$a_{i,j} = \frac{(k+1)^{n(i + j - 1)}}{i + j - 1}, \quad i,j = 1,2,...,n
$$

$$
b_i = \frac{1}{(i+1)^2} (k+1)^{n(i + 1)}(\ln((k+1)^{n(i +1)}) - 1), \quad i = 1,2,...,n
$$

dengan $k = \text{NPM} \mod 4$ dan $n$ adalah banyak persamaan pada sistem\

### Soal

Buatlah suatu program untuk menyelesaikan SPL tersebut secara iteratif menggunakan Gauss-Seidel dengan vektor tebakan awal adalah vektor 0. Input yang diterima program berupa :
1. NPM (integer)
2. Ukuran matriks (integer)
3. Toleransi error (float)
4. Batas iterasi (integer)

Output program berupa matriks diperbesar yang diperoleh, serta tabel yang menampilkan hasil yang didapat setiap iterasi serta nilai error untuk setiap iterasi

### Bonus

Ketentuan berikut tidak harus dikerjakan, tetapi dapat menjadi nilai tambah

Program Anda bisa berjalan berulang kali (dengan beberapa kali input dan output) sesuai permintaan user, tanpa harus berhenti dan di-*run* ulang secara manual terlebih dahulu.

### Contoh Output

In [ ]:
import numpy as np
from numpy import sin, log, sqrt, pi, exp, cos
from tabulate import tabulate

In [ ]:
program()

Masukkan banyak variabel yang ingin diselesaikan dengan SPL: 3
Masukkan NPM Anda:2206026867
maka, nilai k yang digunakan = 3 


Matriks diperbesar yang didapat adalah:
[[6.40000000e+01 2.04800000e+03 8.73813333e+04 7.49339255e+03]
 [2.04800000e+03 8.73813333e+04 4.19430400e+06 3.34281638e+05]
 [8.73813333e+04 4.19430400e+06 2.14748365e+08 1.63950440e+07]]

Akan digunakan metode Gauss-Seidel untuk menyelesaikan SPL
Masukkan besar toleransi error untuk metode Gauss-Seidel: 10**-7
Masukkan banyaknya iterasi maksimal untuk metode Gauss-Seidel: 100

Tabel hasil iterasi Gauss Seidel dari matriks diperbesar tersebut adalah 
╒═══════════╤══════════╤═════════╤════════════╤════════════╕
│  iterasi  │    x1    │   x2    │     x3     │   error    │
╞═══════════╪══════════╪═════════╪════════════╪════════════╡
│     0     │    0     │    0    │     0      │    nan     │
│     1     │ 117.084  │ 1.08139 │ 0.00758282 │  117.084   │
│     2     │ 72.1268  │ 1.7711  │ 0.0124051  │  44.9575   │
│     3  